# Generated by Django 3.2.7 on 2024-03-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_drug_interaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='qty',
            field=models.IntegerField(),
        ),
    ]
