# Generated by Django 3.2.12 on 2024-05-22 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_pharmacy_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='dosage_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('medicine_name', models.CharField(max_length=100)),
                ('dosage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('notes', models.TextField(blank=True, null=True)),
                ('patient_id', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
