# Generated by Django 3.2.12 on 2024-05-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_dosage_tbl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosage_tbl',
            name='dosage',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='dosage_tbl',
            name='notes',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dosage_tbl',
            name='patient_id',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
