# Generated by Django 3.2.12 on 2024-05-22 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0007_auto_20240522_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='caht_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=150)),
                ('doctor_id', models.CharField(max_length=150)),
                ('message', models.CharField(max_length=150)),
                ('reply', models.CharField(max_length=150)),
            ],
        ),
    ]
