# Generated by Django 3.2.12 on 2024-05-22 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0008_caht_tbl'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='caht_tbl',
            new_name='chat_tbl',
        ),
    ]
