# Generated by Django 3.2.12 on 2024-05-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0009_rename_caht_tbl_chat_tbl'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosage_tbl',
            name='status',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
