# Generated by Django 3.2.12 on 2024-05-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0010_dosage_tbl_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosage_tbl',
            name='doctor_id',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
