# Generated by Django 3.2.12 on 2024-06-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0011_dosage_tbl_doctor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='address',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='phone',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
