# Generated by Django 3.2.12 on 2024-06-18 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0012_auto_20240604_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosage_tbl',
            name='description',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
