# Generated by Django 3.2.12 on 2024-06-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0013_dosage_tbl_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosage_tbl',
            name='time',
            field=models.CharField(max_length=150),
        ),
    ]
