# Generated by Django 3.2.12 on 2024-06-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0014_alter_dosage_tbl_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosage_tbl',
            name='no_of_days',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
