# Generated by Django 3.2.12 on 2024-06-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0015_dosage_tbl_no_of_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosage_tbl',
            name='date',
            field=models.CharField(max_length=150),
        ),
    ]
