# Generated by Django 3.2.12 on 2024-08-08 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0016_alter_dosage_tbl_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=150)),
                ('feedbacks', models.CharField(max_length=150)),
            ],
        ),
    ]
