# Generated by Django 3.2.12 on 2024-08-31 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0017_feedback_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='doc_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=150)),
                ('doctor_id', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
                ('fee', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='fee',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
