# Generated by Django 3.2.12 on 2024-08-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0018_auto_20240831_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='consult',
            name='fee',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
