# Generated by Django 3.2.12 on 2024-08-31 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0019_consult_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc_payment',
            name='cardname',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doc_payment',
            name='cardnumber',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doc_payment',
            name='cvv',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doc_payment',
            name='pid',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
