# Generated by Django 3.2.12 on 2024-08-31 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0021_rename_uid_payment_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doc_payment',
            old_name='doctor_id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='user_id',
            new_name='uid',
        ),
        migrations.RemoveField(
            model_name='doc_payment',
            name='patient_id',
        ),
    ]
